// Nations for the home-page marquee / icon cloud. ISO-2 codes chosen so the
// flag emojis render correctly. The 2026 field isn't fully drawn yet, so this
// is a representative set of hosts + likely qualifiers; edit freely.
export const WC_NATIONS: { code: string; name: string }[] = [
  { code: "US", name: "USA" },
  { code: "CA", name: "Canada" },
  { code: "MX", name: "Mexico" },
  { code: "AR", name: "Argentina" },
  { code: "BR", name: "Brazil" },
  { code: "FR", name: "France" },
  { code: "ES", name: "Spain" },
  { code: "DE", name: "Germany" },
  { code: "PT", name: "Portugal" },
  { code: "NL", name: "Netherlands" },
  { code: "BE", name: "Belgium" },
  { code: "IT", name: "Italy" },
  { code: "HR", name: "Croatia" },
  { code: "GB", name: "England" },
  { code: "UY", name: "Uruguay" },
  { code: "CO", name: "Colombia" },
  { code: "JP", name: "Japan" },
  { code: "KR", name: "South Korea" },
  { code: "MA", name: "Morocco" },
  { code: "SN", name: "Senegal" },
  { code: "NG", name: "Nigeria" },
  { code: "GH", name: "Ghana" },
  { code: "EG", name: "Egypt" },
  { code: "CM", name: "Cameroon" },
  { code: "AU", name: "Australia" },
  { code: "EC", name: "Ecuador" },
  { code: "PE", name: "Peru" },
  { code: "CL", name: "Chile" },
  { code: "RS", name: "Serbia" },
  { code: "CH", name: "Switzerland" },
  { code: "DK", name: "Denmark" },
  { code: "PL", name: "Poland" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "IR", name: "Iran" },
  { code: "QA", name: "Qatar" },
  { code: "TN", name: "Tunisia" },
];
